# Generated by Django 6.0.2 on 2026-02-08 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='clothing/%Y/%m/')),
                ('item_type', models.CharField(choices=[('tshirt', 'T-Shirt'), ('shirt', 'Dress Shirt'), ('polo', 'Polo Shirt'), ('sweater', 'Sweater'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('blazer', 'Blazer'), ('coat', 'Coat'), ('jeans', 'Jeans'), ('chinos', 'Chinos'), ('trousers', 'Dress Trousers'), ('shorts', 'Shorts'), ('sneakers', 'Sneakers'), ('boots', 'Boots'), ('dress_shoes', 'Dress Shoes'), ('loafers', 'Loafers'), ('sandals', 'Sandals'), ('belt', 'Belt'), ('watch', 'Watch'), ('tie', 'Tie'), ('hat', 'Hat'), ('scarf', 'Scarf'), ('other', 'Other')], max_length=20)),
                ('colors', models.JSONField(default=list)),
                ('pattern', models.CharField(choices=[('solid', 'Solid'), ('striped', 'Striped'), ('plaid', 'Plaid'), ('checkered', 'Checkered'), ('floral', 'Floral'), ('geometric', 'Geometric'), ('print', 'Print'), ('other', 'Other')], default='solid', max_length=20)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('smart_casual', 'Smart Casual'), ('business_casual', 'Business Casual'), ('formal', 'Formal')], default='casual', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occasion', models.TextField()),
                ('suggestions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
