# Generated by Django 6.0.2 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('tshirt', 'T-Shirt'), ('shirt', 'Dress Shirt'), ('polo', 'Polo Shirt'), ('sweater', 'Sweater'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('blazer', 'Blazer'), ('coat', 'Coat'), ('jeans', 'Jeans'), ('chinos', 'Chinos'), ('trousers', 'Dress Trousers'), ('shorts', 'Shorts'), ('sneakers', 'Sneakers'), ('boots', 'Boots'), ('dress_shoes', 'Dress Shoes'), ('loafers', 'Loafers'), ('sandals', 'Sandals'), ('belt', 'Belt'), ('watch', 'Watch'), ('tie', 'Tie'), ('hat', 'Hat'), ('scarf', 'Scarf'), ('other', 'Other')], max_length=20),
        ),
    ]
