# Generated by Django 6.0.2 on 2026-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_clothingitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('tshirt', 'T-Shirt'), ('shirt', 'Dress Shirt'), ('polo', 'Polo Shirt'), ('sweater', 'Sweater'), ('hoodie', 'Hoodie'), ('tank_top', 'Tank Top'), ('blouse', 'Blouse'), ('crop_top', 'Crop Top'), ('jacket', 'Jacket'), ('blazer', 'Blazer'), ('coat', 'Coat'), ('vest', 'Vest'), ('cardigan', 'Cardigan'), ('jeans', 'Jeans'), ('chinos', 'Chinos'), ('trousers', 'Dress Trousers'), ('shorts', 'Shorts'), ('skirt', 'Skirt'), ('leggings', 'Leggings'), ('dress', 'Dress'), ('jumpsuit', 'Jumpsuit'), ('romper', 'Romper'), ('suit', 'Suit'), ('sneakers', 'Sneakers'), ('boots', 'Boots'), ('dress_shoes', 'Dress Shoes'), ('loafers', 'Loafers'), ('sandals', 'Sandals'), ('heels', 'Heels'), ('flats', 'Flats'), ('belt', 'Belt'), ('watch', 'Watch'), ('tie', 'Tie'), ('bow_tie', 'Bow Tie'), ('hat', 'Hat'), ('scarf', 'Scarf'), ('sunglasses', 'Sunglasses'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('earrings', 'Earrings'), ('ring', 'Ring'), ('bag', 'Bag'), ('backpack', 'Backpack'), ('pocket_square', 'Pocket Square'), ('cufflinks', 'Cufflinks'), ('gloves', 'Gloves'), ('other', 'Other')], max_length=30),
        ),
    ]
