# Generated by Django 6.0.2 on 2026-02-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_alter_clothingitem_item_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clothingitem',
            table='wardrobe_clothing_item',
        ),
        migrations.AlterModelTable(
            name='outfitsuggestion',
            table='wardrobe_outfit_suggestion',
        ),
    ]
