# Generated by Django 6.0.2 on 2026-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_alter_clothingitem_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('outerwear', 'Outerwear'), ('full_body', 'Full Body'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
